root_dir: "/meerschaum"
plugins_dir:
  - "/meerschaum/plugins"
  - "/app/plugins"

project_name: "clone"

sync:
  pipes:

    - connector: "plugin:stress"
      metric: "test"
      columns:
        datetime: "timestamp"
        id: "id"

    - connector: "plugin:noaa"
      metric: "weather"
      columns:
        datetime: "timestamp"
        station: "station"
      parameters:
        noaa:
          stations:
            - "KGMU"
            - "KATL"
            - "KCLT"

    - connector: "plugin:clone"
      metric: "test"
      parameters:
        source:
          pipe:
            connector: "plugin:stress"
            metric: "test"
          backtrack_minutes: 0
          chunk_minutes: 10080

    - connector: "plugin:clone"
      metric: "test"
      location: "combined"
      parameters:
        sources:
          - pipe:
              connector: "plugin:stress"
              metric: "test"
            chunk_minutes: 10080
            backtrack_minutes: 0
          - pipe:
              connector: "plugin:noaa"
              metric: "weather"
            backtrack_minutes: 1440
            chunk_minutes: 10080
            params:
              station:
                - "_KCLT"

plugins:
  - "stress"
  - "noaa"

config:
  meerschaum:
    instance: "sql:main"
    connectors:
      sql:
        main: MRSM{meerschaum:connectors:sql:main}

environment: {}
